# Basic configs
[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ["lib"]

# Compiler configs
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

# Gas reporting configs
gas_reports=[
    "Vault",
    "Trader",
    "RoleManager"
]

# File system configs
allow_paths = ["./node_modules"]
fs_permissions = [{ access = "read-write", path = "./"}]
extra_output = ["storageLayout"]

# Testing configs
ffi = true
block_number = 0
[profile.default.fuzz]
runs = 1000
[profile.pr.fuzz]
runs = 10000
[profile.ci.fuzz]
runs = 100000

# Formatting configs
[fmt]
line_length = 80
number_underscore = "thousands"
single_line_statement_blocks = "preserve"
multiline_func_header = "all"
sort_imports = true
contract_new_lines = true
override_spacing = false
wrap_comments = true
tab_width = 4
ignore = []


# Deployment configs
[rpc_endpoints]
sepolia = "https://eth-sepolia.public.blastapi.io"
arbitrumSepolia = "https://arbitrum-sepolia-rpc.publicnode.com"
baseMainnet = "https://base.llamarpc.com"